site_name: BCMSL React DevOps Guidelines
site_author: Anill Maraj
copyright: Blue Coconut Multimedia Solutions Limited © 2023
repo_name: bluecoconutltd/BCMSL_DevOps_Guidelines
repo_url: https://github.com/bluecoconutltd/BCMSL_DevOps_Guidelines
edit_uri: edit/main/docs/

## Navigation Configuration
nav:
    - Guidelines: index.md
    - 0. Requirements: required.md
    - 1. Create Project: create.md
    - 2. Version Control: version.md
    - 3. Modify Project: modify.md
    - 4. View Project: view.md
    - 5. Build Project: build.md
    - 6. References: reference.md
    - License: license.md
    - Notes: notes.md
    - Changelog: changelog.md

## Theme Configuration
theme:
  name: material
  custom_dir: overrides
  logo: assets/img/BCMSL LOGO LIGHT ICON.svg
  favicon: assets/img/favicon.ico
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/code-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: BCMSL_LIGHT
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  font:
    text: Open Sans
    code: Inconsolata
  features:
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips

## Extra CSS Configuration
extra_css:
  - assets/css/main.css

## Extra JS Configuration
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/js/tablesort.js
  - assets/js/main.js

## Extra Context Configuration
extra:
  homepage: https://bluecoconut.ltd
  version:
    provider: mike
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: false
    actions:
      - accept
      - manage
  copyright: >
    Copyright &copy; 2017 - 2023 Blue Coconut Multimedia Solutions Limited –
    <a href="#__consent">Manage Settings</a>
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bluecoconutltd
      name: Blue Coconut Multimedia Solutions Limited
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/bluecoconutltd
      name: Blue Coconut Multimedia Solutions Limited
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/bluecoconutltd
      name: Blue Coconut Multimedia Solutions Limited
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/bluecoconutltd
      name: Blue Coconut Multimedia Solutions Limited
    - icon: fontawesome/brands/github
      link: https://github.com/bluecoconutltd
      name: Blue Coconut Multimedia Solutions Limited
  generator: false

## MarkDown Extensions Configuration
markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - md_in_html
    - footnotes
    - tables
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.betterem
    - pymdownx.smartsymbols
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
        options:
          custom_icons:
            - overrides/.icons
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.tabbed:
        alternate_style: true

# Plugins Configuration
plugins:
    - search:
        separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
    - glightbox
    - git-authors
    - git-revision-date-localized:
        enable_creation_date: true
        type: timeago
    - git-committers:
        repository: bluecoconutltd/BCMSL_DevOps_Guidelines
        branch: main
    - offline
